# Generated by Django 5.1.3 on 2025-01-08 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default='premchand', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books_api.author'),
            preserve_default=False,
        ),
    ]
